package faang.school.accountservice.enums;

public enum AccountType {
    PERSONALCHECKING,
    PERSONALSAVINGS,
    PERSONALCURRENCY,
    BUSINESSCHECKING,
    BUSINESSSAVINGS,
    BUSINESSCURRENCY,
    JOINTACCOUNT,
    TRUSTACCOUNT,
    CORPORATEACCOUNT,
    INVESTMENTACCOUNT,
    RETIREMENTACCOUNT,
    ESCROWACCOUNT,
    STUDENTACCOUNT,
    FIXEDDEPOSIT,
    CREDITACCOUNT
}
