package faang.school.accountservice.enums;

public enum PaymentAccountType {
    PERSONAL_CHECKING_ACCOUNT,
    BUSINESS_CHECKING_ACCOUNT,
    SAVINGS_ACCOUNT,
    BUSINESS_SAVINGS_ACCOUNT,
    FOREIGN_CURRENCY_ACCOUNT,
    CREDIT_ACCOUNT,
    DEPOSIT_ACCOUNT,
    ACCUMULATIVE_ACCOUNT,
    INVESTMENT_ACCOUNT
}
