spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
    properties:
      acks: 1
      retries: 1
      enable.idempotence: true
      request.timeout.ms: 30000
      max.block.ms: 60000
    topic:
      payments:
          authorization:
            request: payment.authorization-request
            response: payment.authorization-response
          clearing:
            request: payment.clearing-request
            response: payment.clearing-response
          cancel:
            request: payment.cancel-request
            response: payment.cancel-response

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090
  shutdown: graceful

springdoc:
  swagger-ui:
    persist-authorization: true

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080