spring:
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    properties:
      auto.create.topics.enable: true
      acks: all
      retries: 1
      enable.idempotence: true
      request.timeout.ms: 30000
      max.block.ms: 60000


    topic:
      payments:
        authorization:
          request: payment.authorization-request
          response: payment.authorization-response
        clearing:
          request: payment.clearing-request
          response: payment.clearing-response
        cancel:
          request: payment.cancel-request
          response: payment.cancel-response