spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-testLiquibase.yaml

redis:
  topic:
    pending_operation: pending_operation
    checking_balance: checking_balance

app:
  messaging: redis