TRUNCATE TABLE transfer_requests RESTART IDENTITY CASCADE;
TRUNCATE TABLE auth_payment RESTART IDENTITY CASCADE;
TRUNCATE TABLE balance RESTART IDENTITY CASCADE;
TRUNCATE TABLE account RESTART IDENTITY CASCADE;
TRUNCATE TABLE balance_audit RESTART IDENTITY CASCADE;