CREATE TABLE IF NOT EXISTS account (
    id BIGSERIAL PRIMARY KEY,
    number VARCHAR(20) NOT NULL UNIQUE,
    owner VARCHAR(20) NOT NULL,
    type VARCHAR(50) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    closed_at TIMESTAMP NULL,
    version INT DEFAULT 1 NOT NULL
);

CREATE INDEX idx_account_owner ON account(owner);
CREATE INDEX idx_account_number ON account(number);

INSERT INTO account (number, owner, type, currency, status, created_at, updated_at, closed_at, version) VALUES
('ACC001', 'John Doe', 'CORPORATEACCOUNT', 'USD', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1),
('ACC002', 'Jane Smith', 'CREDITACCOUNT', 'EUR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1),
('ACC003', 'Robert Brown', 'TRUSTACCOUNT', 'EUR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1),
('ACC004', 'Emily Davis', 'CORPORATEACCOUNT', 'USD', 'BLOCK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1),
('ACC005', 'Michael Wilson', 'INVESTMENTACCOUNT', 'EUR', 'CLOSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);