
CREATE TABLE account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number  VARCHAR(20) NOT NULL,
  user_id         BIGINT,
  project_id      BIGINT,
  type            VARCHAR(30) NOT NULL,
  currency        CHAR(3) NOT NULL,
  status          VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at       TIMESTAMPTZ,
  version         INT NOT NULL DEFAULT 0
);

ALTER TABLE account ADD CONSTRAINT account_number_uk UNIQUE (account_number);

CREATE INDEX account_number_idx ON account (account_number);
CREATE INDEX account_user_id_idx ON account (user_id);
CREATE INDEX account_project_id_idx ON account (project_id);

ALTER TABLE account
  ADD CONSTRAINT account_user_fk
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  ADD CONSTRAINT account_project_fk
    FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE RESTRICT;

