CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_uuid UUID DEFAULT gen_random_uuid() NOT NULL,
  user_id         BIGINT
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
  request_type    VARCHAR(30) NOT NULL DEFAULT 'CREATE',
  lock_value      VARCHAR(255) NOT NULL,
  is_open         BOOLEAN NOT NULL,
  request_data    VARCHAR(255) NOT NULL,
  status          VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',
  status_details  VARCHAR(255) NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version         INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_id ON requests(user_id);
CREATE UNIQUE INDEX idx_lock_unique
ON requests(user_id, lock_value)
WHERE status = 'open';
CREATE INDEX idx_status ON requests(status);
CREATE INDEX idx_user_status_time
ON requests(user_id, status, created_at);


