-- СОЗДАНИЕ ТАБЛИЦЫ BALANCE
CREATE TABLE IF NOT EXISTS BALANCE (
    ID BIGSERIAL PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL CHECK (ACCOUNT_NUMBER ~ '^\d{12,20}$'),
    AUTHORIZATION_BALANCE NUMERIC(19,4) NOT NULL,
    ACTUAL_BALANCE NUMERIC(19,4) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0
    );

-- СОЗДАНИЕ ТАБЛИЦЫ ACCOUNT
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID BIGSERIAL PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL CHECK (ACCOUNT_NUMBER ~ '^\d{12,20}$'),
    USER_ID BIGINT,
    PROJECT_ID BIGINT,
    TYPE VARCHAR(50) NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMPTZ,
    BALANCE_ID BIGINT,
    VERSION BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT FK_BALANCE FOREIGN KEY (BALANCE_ID) REFERENCES BALANCE (ID) ON DELETE SET NULL
    );

-- СОЗДАНИЕ ИНДЕКСА ДЛЯ ПОИСКА ПО USER_ID
CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_USER_ID ON ACCOUNT(USER_ID);