CREATE TABLE IF NOT EXISTS balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    authorisation_balance DECIMAL(19, 2) NOT NULL,
    factual_balance DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_account
        FOREIGN KEY (account_number)
        REFERENCES account (account_number)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT pk_balance PRIMARY KEY (id)
)