CREATE TABLE request (
  id UUID NOT NULL,
   context VARCHAR(255),
   request_status SMALLINT,
   scheduled_at TIMESTAMP WITHOUT TIME ZONE,
   account_id BIGINT NOT NULL,
   owner_id BIGINT NOT NULL,
   balance_id BIGINT NOT NULL,
   CONSTRAINT pk_request PRIMARY KEY (id)
);

ALTER TABLE request ADD CONSTRAINT FK_REQUEST_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

ALTER TABLE request ADD CONSTRAINT FK_REQUEST_ON_BALANCE FOREIGN KEY (balance_id) REFERENCES balance (id);

ALTER TABLE request ADD CONSTRAINT FK_REQUEST_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owner (id);

