CREATE TABLE IF NOT EXISTS REQUEST
(
    IDEMPOTENCY_TOKEN  UUID PRIMARY KEY,
    USER_ID            BIGINT      NOT NULL,
    REQUEST_TYPE       VARCHAR(32) NOT NULL,
    VALUE_LOCK         TEXT,
    IS_OPEN            BOOLEAN     NOT NULL DEFAULT TRUE,
    REQUEST_INPUT_DATA JSON,
    STATUS             VARCHAR(32) NOT NULL,
    STATUS_DESCRIPTION TEXT,
    CREATED_AT         TIMESTAMP            DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP            DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VERSION            BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS IDX_REQUEST_USER_ID ON REQUEST (USER_ID);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNIQUE_OPEN_LOCK_VALUE
    ON REQUEST (VALUE_LOCK)
    WHERE IS_OPEN = TRUE;