CREATE TABLE IF NOT EXISTS tariff
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    rate_history JSONB,
    create_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);