INSERT INTO account_numbers_sequence (type)
VALUES
    ('CHECKING_ACCOUNT_INDIVIDUAL'),
    ('CHECKING_ACCOUNT_LEGAL_ENTITY'),
    ('CURRENCY_ACCOUNT'),
    ('SAVING_ACCOUNT'),
    ('INVESTMENT_ACCOUNT')