CREATE TABLE tariff
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         SMALLINT         NOT NULL,
    current_rate DECIMAL(19, 4)   NOT NULL
);

CREATE TABLE savings_account
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                BIGINT            NOT NULL,
    current_rate              DECIMAL(19, 4)    NOT NULL,
    last_date_before_interest TIMESTAMP         NOT NULL,
    version                   BIGINT            NOT NULL,
    date_of_creation          TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_of_update            TIMESTAMP         DEFAULT CURRENT_TIMESTAMP,
    tariff_id                 BIGINT            NOT NULL,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_tariff FOREIGN KEY (tariff_id) REFERENCES tariff (id)
);
