CREATE TABLE tariff
(
    id           BIGSERIAL PRIMARY KEY,
    type         SMALLINT       NOT NULL,
    current_rate DECIMAL(19, 4) NOT NULL,
    betting_history NUMERIC(19, 4)[]
);

CREATE TABLE savings_accounts
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                     BIGINT         NOT NULL,
    current_rate                   DECIMAL(19, 2) NOT NULL,
    last_interest_calculation_date TIMESTAMP      NOT NULL,
    created_at                     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                     TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    tariff_id                      BIGINT         NOT NULL,
    version                        BIGINT         NOT NULL,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_tariff FOREIGN KEY (tariff_id) REFERENCES tariff (id)
);
