CREATE TABLE account_schema.balance
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authorisation_balance DECIMAL                                 NOT NULL,
    actual_balance        DECIMAL                                 NOT NULL,
    account_id            BIGINT,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    version               BIGINT                                  NOT NULL,
    CONSTRAINT pk_balance PRIMARY KEY (id)
);

ALTER TABLE account_schema.balance
    ADD CONSTRAINT uc_balance_account UNIQUE (account_id);

ALTER TABLE account_schema.balance
    ADD CONSTRAINT FK_BALANCE_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account_schema.account (id);

ALTER TABLE account_schema.balance
    ADD CONSTRAINT chk_positive_balances CHECK (authorisation_balance >= 0 AND actual_balance >= 0);

ALTER TABLE account_schema.balance
    ALTER COLUMN authorisation_balance SET DEFAULT 0;

ALTER TABLE account_schema.balance
    ALTER COLUMN actual_balance SET DEFAULT 0;